#!/usr/bin/env python3
"""Bake the touch-lock glyph into src/components/icons/touch_lock_icon.h.

    python3 scripts/gen_touch_lock_icon.py

One icon: the padlock drawn in place of the button hint boxes when touch is
switched off (docs/touch-modes.md). Same freeink::Icon output format and the
same cairosvg/rsvg fallback as scripts/gen_map_header_icons.py -- see that
script's header for why this does not call the SDK's own generator.

20px because the glyph sits inside the strip that replaces the 40px hint band on
an X4-sized panel, with room to breathe above and below. A bigger panel scales
the strip, not the glyph: a padlock is an indicator, not a target.
"""
import io
import os
import re
import shutil
import subprocess
import sys

from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUCIDE = os.path.join(REPO, "freeink-sdk/libs/assets/Icons/lucide/icons")
OUT = os.path.join(REPO, "src/components/icons/touch_lock_icon.h")

THRESHOLD = 110
SIZE = 20

LUCIDE_ICONS = [
    ("touchLock", "lock", SIZE),
]


def rasterise(svg_path, width, height):
    if shutil.which("rsvg-convert"):
        png = subprocess.run(
            ["rsvg-convert", "-w", str(width), "-h", str(height), svg_path],
            capture_output=True,
            check=True,
        ).stdout
    else:
        import cairosvg

        png = cairosvg.svg2png(url=svg_path, output_width=width, output_height=height)
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    flat = Image.new("RGBA", img.size, (255, 255, 255, 255))
    flat.paste(img, mask=img.split()[3])
    return flat.convert("L")


def pack(img):
    """-> (bytes, opticalCenterY). 1 = transparent, 0 = ink, MSB first."""
    width, height = img.size
    pixels = img.load()
    data = []
    sum_y = 0
    count = 0
    for y in range(height):
        for x_byte in range(0, width, 8):
            byte = 0
            for bit in range(8):
                x = x_byte + bit
                white = 1
                if x < width and pixels[x, y] < THRESHOLD:
                    white = 0
                    sum_y += y
                    count += 1
                byte |= white << (7 - bit)
            data.append(byte)
    return data, (round(sum_y / count) if count else height // 2)


def ident(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def emit(alias, img, note):
    data, centre = pack(img)
    width, height = img.size
    bits = f"icon_{ident(alias)}_bits"
    body = ", ".join(f"0x{b:02X}" for b in data)
    return [
        f"// {note}",
        f"static const uint8_t {bits}[] = {{{body}}};",
        f"static const freeink::Icon icon_{ident(alias)} = "
        f"{{{width}, {height}, {centre}, {bits}}};",
        "",
    ]


def main():
    out = [
        "#pragma once",
        "",
        "#include <Icon.h>",
        "",
        "#include <cstdint>",
        "",
        "// Generated by scripts/gen_touch_lock_icon.py. Do not edit.",
        f"// {SIZE}px, drawn with GfxRenderer::drawMono1bpp().",
        "",
    ]

    for alias, lucide, size in LUCIDE_ICONS:
        svg = os.path.join(LUCIDE, lucide + ".svg")
        if not os.path.exists(svg):
            sys.exit(f"missing svg for '{alias}': {svg}")
        out += emit(alias, rasterise(svg, size, size), f"{alias}  (lucide: {lucide})")

    with open(OUT, "w") as handle:
        handle.write("\n".join(out))
    if shutil.which("clang-format"):
        subprocess.run(["clang-format", "-i", OUT], check=True)
    else:
        print("warning: clang-format not found -- run it on the output before committing")
    print(f"wrote {OUT}: {len(LUCIDE_ICONS)} icons")


if __name__ == "__main__":
    main()
