#!/usr/bin/env python3
"""Bake src/images/mountains.svg into src/images/Mountains.h.

    python3 scripts/gen_mountains.py

The mountain line art on its own, with no logo and no wordmark over it -- the
horizon the trip-picker's empty state draws its backpack mark above
(src/activities/map/RouteEmptyActivity.cpp).

## Why 700 wide, which is wider than any panel

The horizon has to run off both edges. A silhouette that ends inside the
screen reads as a picture of mountains; one that leaves the frame reads as
terrain the rider is standing in. So the asset is deliberately wider than the
widest panel here (540) and the screen centres it and clips.

**Clipping is the screen's job, not `drawMono1bpp`'s.** `GfxRenderer::drawPixel()`
LOG_ERRs on every out-of-range pixel rather than dropping it quietly, so
blitting this straight would be tens of thousands of serial lines per frame --
the screen that draws it carries its own clipped blit.

Threshold rather than dithering: at this width the traced ridge lines are
1-2 px and dithering eats them.
"""
import io
import os
import sys

import cairosvg
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SVG = os.path.join(REPO, "src/images/mountains.svg")
OUT = os.path.join(REPO, "src/images/Mountains.h")

# Wider than the widest panel, in device pixels, so the ridge runs off both
# edges. Height follows the SVG's own aspect ratio (1842x722), so the
# mountains are not squashed.
WIDTH = 700
HEIGHT = 274
THRESHOLD = 215


def rasterise(svg_path, width, height):
    png = cairosvg.svg2png(url=svg_path, output_width=width, output_height=height)
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    flat = Image.new("RGBA", img.size, (255, 255, 255, 255))
    flat.paste(img, mask=img.split()[3])
    return flat.convert("L")


def pack(img, name):
    """1bpp, MSB first, 1 = white -- the convention every image in src/images uses."""
    width, height = img.size
    pixels = img.tobytes()  # L mode: one byte per pixel, row-major
    out = bytearray()
    for y in range(height):
        for x in range(0, width, 8):
            byte = 0
            for bit in range(8):
                if x + bit < width and pixels[y * width + x + bit] >= THRESHOLD:
                    byte |= 1 << (7 - bit)
            out.append(byte)

    body = ""
    for i, value in enumerate(out):
        body += f"0x{value:02X}, "
        if (i + 1) % 16 == 0:
            body += "\n    "

    return (
        "#pragma once\n#include <cstdint>\n\n"
        "// Generated by scripts/gen_mountains.py from src/images/mountains.svg.\n"
        f"// {width}x{height}, row-major, stride {(width + 7) // 8} bytes, MSB first,\n"
        "// bit 1 = leave the pixel, bit 0 = ink. NOT pre-rotated -- drawn with\n"
        "// GfxRenderer::drawMono1bpp(), which applies the orientation itself.\n"
        f"#define MOUNTAINS_WIDTH {width}\n"
        f"#define MOUNTAINS_HEIGHT {height}\n"
        f"static const uint8_t {name}[] = {{\n    " + body.rstrip(", \n") + "\n};\n"
    )


def main():
    if not os.path.exists(SVG):
        sys.exit(f"missing {SVG}")
    img = rasterise(SVG, WIDTH, HEIGHT)
    with open(OUT, "w") as handle:
        handle.write(pack(img, "Mountains"))
    print(f"Wrote {OUT} ({os.path.getsize(OUT) // 1024} kB source, " f"{WIDTH * HEIGHT // 8 // 1024} kB bitmap in flash)")


if __name__ == "__main__":
    main()
